### PR TITLE
ts

### PR DESCRIPTION
**Pull request by SkyBlockDev**

### CODE REVIEW

**Comment by SirObby** [comment]
You still have node_modules there

**Comment by SkyBlockDev** [comment]
> You still have node_modules there

you are supposed to have a .gitignore

**Comment by SirObby** [comment]
Look at your PR dude it has node_modules there

**Comment by SkyBlockDev** [comment]
> Look at your PR dude it has node_modules there

yeah LOOK AT your repo your supposed to have a .gitignore

**Comment by SirObby** [comment]
I dont have a .gitignore yet lol

**Comment by SirObby** [comment]
and I also havent ever needed one

**Comment by SkyBlockDev** [comment]
> I dont have a .gitignore yet lol

ehh you can you can remove the node modules after you accepted the pr

**Comment by SirObby** [comment]
wait im trying this on my pc rq

**Comment by SirObby** [comment]
Also can't you just remove it from your PR?

**Comment by SkyBlockDev** [comment]
> and I also havent ever needed one



> Also can't you just remove it from your PR?

no i already deleted

**Comment by SirObby** [comment]
ok

**Comment by SirObby** [comment]
Imma test this now btw

**Comment by SkyBlockDev** [comment]
> Imma test this now btw

nice

**Comment by SkyBlockDev** [comment]
> Imma test this now btw

i added script

**Comment by SirObby** [comment]
wait lemme see

**Comment by SirObby** [comment]
what script?

**Comment by SirObby** [comment]
what script?

**Comment by SkyBlockDev** [comment]
> what script?

packagejson

**Comment by SirObby** [comment]
oh the build one

**Comment by SirObby** [comment]
error TS18003: No inputs were found in config file 'C:/Users/ccamb/Downloads/BlobDiscord-rs/BlobDiscord-rs/tsconfig.json'. Specified 'include' paths were '["src/**/*"]' and 'exclude' paths were '["node_modules"]'.

**Comment by SkyBlockDev** [comment]
> error TS18003: No inputs were found in config file 'C:/Users/ccamb/Downloads/BlobDiscord-rs/BlobDiscord-rs/tsconfig.json'. Specified 'include' paths were '["src/**/*"]' and 'exclude' paths were '["node_modules"]'.

put the js files in a folder called src

**Comment by SirObby** [comment]
What do you mean?

**Comment by SkyBlockDev** [comment]
put all the ts files in a folder called src

**Comment by SirObby** [comment]
including the cmds folder?

**Comment by SkyBlockDev** [comment]
yes

**Comment by SirObby** [comment]
Wait so do I need all of the code related files in src?
Including config.json?

**Comment by SkyBlockDev** [comment]
bruh only ts

**Comment by SirObby** [comment]
node_modules/typescript/lib/lib.dom.d.ts:20004:18 - error TS2451: Cannot redeclare block-scoped variable 'fetch'.

20004 declare function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
                       ~~~~~

  src/bot.ts:9:7
    9 const fetch = require('node-fetch');
            ~~~~~
    'fetch' was also declared here.
  src/cmds/stats.ts:2:7
    2 const fetch = require('node-fetch');
            ~~~~~
    and here.

src/bot.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/cmds/ban.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.
  src/cmds/eval.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    and here.
  src/cmds/help.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    and here.
  src/cmds/info.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    and here.
  src/cmds/kick.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    and here.

src/bot.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'configs'.

3 const configs = require('./configs.json')
        ~~~~~~~

  src/command.ts:1:7
    1 const configs = require('./configs.json')
            ~~~~~~~
    'configs' was also declared here.
  src/slashhandler.ts:1:7
    1 const configs = require('./configs.json')
            ~~~~~~~
    and here.

src/bot.ts:4:7 - error TS2451: Cannot redeclare block-scoped variable 'fs'.

4 const fs = require("fs")
        ~~

  src/slashhandler.ts:2:7
    2 const fs = require('fs');
            ~~
    'fs' was also declared here.
  src/cmds/ban.ts:2:7
    2 const fs = require('fs')
            ~~
    and here.
  src/cmds/kick.ts:2:7
    2 const fs = require('fs')
            ~~
    and here.
  src/cmds/mute.ts:2:7
    2 const fs = require('fs')
            ~~
    and here.

src/bot.ts:9:7 - error TS2451: Cannot redeclare block-scoped variable 'fetch'.

9 const fetch = require('node-fetch');
        ~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:20004:18
    20004 declare function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
                           ~~~~~
    'fetch' was also declared here.

src/bot.ts:15:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

15 const ytdl = require('ytdl-core');
         ~~~~

  src/cmds/play.ts:4:7
    4 const ytdl = require('ytdl-core');
            ~~~~
    'ytdl' was also declared here.
  src/cmds/queue.ts:4:7
    4 const ytdl = require('ytdl-core');
            ~~~~
    and here.
  src/cmds/skip.ts:4:7
    4 const ytdl = require('ytdl-core');
            ~~~~
    and here.
  src/cmds/stop.ts:4:7
    4 const ytdl = require('ytdl-core');
            ~~~~
    and here.
  src/slashes/play.ts:3:7
    3 const ytdl = require('ytdl-core');
            ~~~~
    and here.

src/bot.ts:79:9 - error TS2304: Cannot find name 'songEmbedYTDL'.

79         songEmbedYTDL = new Discord.MessageEmbed()
           ~~~~~~~~~~~~~

src/bot.ts:91:75 - error TS2304: Cannot find name 'songEmbedYTDL'.

91         new Discord.WebhookClient(client.user.id, interaction.token).send(songEmbedYTDL)
                                                                             ~~~~~~~~~~~~~

src/bot.ts:130:5 - error TS2304: Cannot find name 'songEmbedYTDL'.

130     songEmbedYTDL = new Discord.MessageEmbed()
        ~~~~~~~~~~~~~

src/bot.ts:143:14 - error TS2304: Cannot find name 'songEmbedYTDL'.

143     msg.edit(songEmbedYTDL)
                 ~~~~~~~~~~~~~

src/bot.ts:145:30 - error TS2304: Cannot find name 'songEmbedYTDL'.

145         message.channel.send(songEmbedYTDL)
                                 ~~~~~~~~~~~~~

src/bot.ts:152:10 - error TS2393: Duplicate function implementation.

152 function secondsToString(seconds) {
             ~~~~~~~~~~~~~~~

src/bot.ts:156:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'seconds' must be of type 'any', but here has type 'number'.    

156     var seconds = Math.floor(seconds % 60);
            ~~~~~~~

  src/bot.ts:152:26
    152 function secondsToString(seconds) {
                                 ~~~~~~~
    'seconds' was also declared here.

src/bot.ts:164:9 - error TS2322: Type 'string' is not assignable to type 'number'.

164         hours = "0" + hours;
            ~~~~~

src/bot.ts:167:9 - error TS2322: Type 'string' is not assignable to type 'number'.

167         minutes = "0" + minutes;
            ~~~~~~~

src/callfunc.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

1 const bot = require('./bot.js')
        ~~~

  src/cmds/play.ts:3:7
    3 const bot = require('../bot.js')
            ~~~
    'bot' was also declared here.
  src/cmds/queue.ts:3:7
    3 const bot = require('../bot.js')
            ~~~
    and here.
  src/cmds/skip.ts:3:7
    3 const bot = require('../bot.js')
            ~~~
    and here.
  src/cmds/stop.ts:3:7
    3 const bot = require('../bot.js')
            ~~~
    and here.
  src/slashes/play.ts:2:7
    2 const bot = require('../bot.js')
            ~~~
    and here.

src/cmds/ban.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/ban.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'fs'.

2 const fs = require('fs')
        ~~

  src/bot.ts:4:7
    4 const fs = require("fs")
            ~~
    'fs' was also declared here.

src/cmds/eval.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/eval.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'commandHandler'.

2 const commandHandler = require('../command.js');
        ~~~~~~~~~~~~~~

  src/cmds/play.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    'commandHandler' was also declared here.
  src/cmds/queue.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    and here.
  src/cmds/skip.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    and here.
  src/cmds/stop.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    and here.

src/cmds/help.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/info.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/kick.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/kick.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'fs'.

2 const fs = require('fs')
        ~~

  src/bot.ts:4:7
    4 const fs = require("fs")
            ~~
    'fs' was also declared here.

src/cmds/mute.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/mute.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'fs'.

2 const fs = require('fs')
        ~~

  src/bot.ts:4:7
    4 const fs = require("fs")
            ~~
    'fs' was also declared here.

src/cmds/ping.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/play.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/play.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'commandHandler'.

2 const commandHandler = require('../command.js');
        ~~~~~~~~~~~~~~

  src/cmds/eval.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    'commandHandler' was also declared here.

src/cmds/play.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

3 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/cmds/play.ts:4:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

4 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/cmds/queue.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/queue.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'commandHandler'.

2 const commandHandler = require('../command.js');
        ~~~~~~~~~~~~~~

  src/cmds/eval.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    'commandHandler' was also declared here.

src/cmds/queue.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

3 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/cmds/queue.ts:4:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

4 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/cmds/queue.ts:22:10 - error TS2405: The left-hand side of a 'for...in' statement must be of type 'string' or 'any'.

22     for (length in queue[message.guild.id]) {
            ~~~~~~

src/cmds/skip.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/skip.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'commandHandler'.

2 const commandHandler = require('../command.js');
        ~~~~~~~~~~~~~~

  src/cmds/eval.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    'commandHandler' was also declared here.

src/cmds/skip.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

3 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/cmds/skip.ts:4:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

4 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/cmds/stats.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/stats.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'fetch'.

2 const fetch = require('node-fetch');
        ~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:20004:18
    20004 declare function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
                           ~~~~~
    'fetch' was also declared here.

src/cmds/stats.ts:4:10 - error TS2393: Duplicate function implementation.

4 function secondsToString(seconds) {
           ~~~~~~~~~~~~~~~

src/cmds/stats.ts:8:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'seconds' must be of type 'any', but here has type 'number'.

8     var seconds = Math.floor(seconds % 60);
          ~~~~~~~

  src/cmds/stats.ts:4:26
    4 function secondsToString(seconds) {
                               ~~~~~~~
    'seconds' was also declared here.

src/cmds/stats.ts:16:9 - error TS2322: Type 'string' is not assignable to type 'number'.

16         hours = "0" + hours;
           ~~~~~

src/cmds/stats.ts:19:9 - error TS2322: Type 'string' is not assignable to type 'number'.

19         minutes = "0" + minutes;
           ~~~~~~~

src/cmds/stop.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/stop.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'commandHandler'.

2 const commandHandler = require('../command.js');
        ~~~~~~~~~~~~~~

  src/cmds/eval.ts:2:7
    2 const commandHandler = require('../command.js');
            ~~~~~~~~~~~~~~
    'commandHandler' was also declared here.

src/cmds/stop.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

3 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/cmds/stop.ts:4:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

4 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/cmds/unplug.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/uptime.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/cmds/uptime.ts:7:10 - error TS2393: Duplicate function implementation.

7 function secondsToString(seconds) {
           ~~~~~~~~~~~~~~~

src/cmds/uptime.ts:11:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'seconds' must be of type 'any', but here has type 'number'.

11     var seconds = Math.floor(seconds % 60);
           ~~~~~~~

  src/cmds/uptime.ts:7:26
    7 function secondsToString(seconds) {
                               ~~~~~~~
    'seconds' was also declared here.

src/cmds/uptime.ts:19:9 - error TS2322: Type 'string' is not assignable to type 'number'.

19         hours = "0" + hours;
           ~~~~~

src/cmds/uptime.ts:22:9 - error TS2322: Type 'string' is not assignable to type 'number'.

22         minutes = "0" + minutes;
           ~~~~~~~

src/command.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'configs'.

1 const configs = require('./configs.json')
        ~~~~~~~

  src/bot.ts:3:7
    3 const configs = require('./configs.json')
            ~~~~~~~
    'configs' was also declared here.

src/command.ts:2:5 - error TS2451: Cannot redeclare block-scoped variable 'cache'.

2 let cache = []
      ~~~~~

  src/slashhandler.ts:4:5
    4 let cache = []
          ~~~~~
    'cache' was also declared here.

src/command.ts:3:5 - error TS2451: Cannot redeclare block-scoped variable 'prefix'.

3 let prefix = "blub"
      ~~~~~~

  src/slashhandler.ts:5:5
    5 let prefix = configs.prefix
          ~~~~~~
    'prefix' was also declared here.

src/slashes/info.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/ping.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/play.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/play.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

2 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/slashes/play.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

3 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/slashes/queue.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/queue.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

2 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/slashes/queue.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

3 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/slashes/queue.ts:25:10 - error TS2405: The left-hand side of a 'for...in' statement must be of type 'string' or 'any'.

25     for (length in queue[interaction.guild_id]) {
            ~~~~~~

src/slashes/skip.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/skip.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

2 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/slashes/skip.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

3 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/slashes/skip.ts:32:20 - error TS2552: Cannot find name 'message'. Did you mean 'onmessage'?

32             return message.reply('You can\'t skip if there is nothing to play after this!');
                      ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:20013:13
    20013 declare var onmessage: ((this: Window, ev: MessageEvent) => any) | null;
                      ~~~~~~~~~
    'onmessage' is declared here.

src/slashes/stats.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/stats.ts:3:10 - error TS2393: Duplicate function implementation.

3 function secondsToString(seconds) {
           ~~~~~~~~~~~~~~~

src/slashes/stats.ts:7:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'seconds' must be of type 'any', but here has type 'number'.

7     var seconds = Math.floor(seconds % 60);
          ~~~~~~~

  src/slashes/stats.ts:3:26
    3 function secondsToString(seconds) {
                               ~~~~~~~
    'seconds' was also declared here.

src/slashes/stats.ts:15:9 - error TS2322: Type 'string' is not assignable to type 'number'.

15         hours = "0" + hours;
           ~~~~~

src/slashes/stats.ts:18:9 - error TS2322: Type 'string' is not assignable to type 'number'.

18         minutes = "0" + minutes;
           ~~~~~~~

src/slashes/stop.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/stop.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'bot'.

2 const bot = require('../bot.js')
        ~~~

  src/callfunc.ts:1:7
    1 const bot = require('./bot.js')
            ~~~
    'bot' was also declared here.

src/slashes/stop.ts:3:7 - error TS2451: Cannot redeclare block-scoped variable 'ytdl'.

3 const ytdl = require('ytdl-core');
        ~~~~

  src/bot.ts:15:7
    15 const ytdl = require('ytdl-core');
             ~~~~
    'ytdl' was also declared here.

src/slashes/stop.ts:17:16 - error TS1308: 'await' expressions are only allowed within async functions and at the top levels of modules.

17   let member = await client.guilds.cache.get(interaction.guild_id).members.fetch(interaction.member.user.id)
                  ~~~~~

  src/slashes/stop.ts:5:19
    5 exports.execute = (interaction, args, client) => {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/slashes/stop.ts:24:22 - error TS1308: 'await' expressions are only allowed within async functions and at the top levels of modules.

24         connection = await member.voice.channel.join();
                        ~~~~~

  src/slashes/stop.ts:5:19
    5 exports.execute = (interaction, args, client) => {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to mark this function as 'async'?

src/slashes/stop.ts:28:19 - error TS2552: Cannot find name 'message'. Did you mean 'onmessage'?

28             queue[message.guild.id] = undefined;
                     ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:20013:13
    20013 declare var onmessage: ((this: Window, ev: MessageEvent) => any) | null;
                      ~~~~~~~~~
    'onmessage' is declared here.

src/slashes/stop.ts:30:13 - error TS2552: Cannot find name 'message'. Did you mean 'onmessage'?

30             message.member.voice.channel.leave()
               ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:20013:13
    20013 declare var onmessage: ((this: Window, ev: MessageEvent) => any) | null;
                      ~~~~~~~~~
    'onmessage' is declared here.

src/slashes/uptime.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Discord'.

1 const Discord = require('discord.js');
        ~~~~~~~

  src/bot.ts:1:7
    1 const Discord = require('discord.js');
            ~~~~~~~
    'Discord' was also declared here.

src/slashes/uptime.ts:3:10 - error TS2393: Duplicate function implementation.

3 function secondsToString(seconds) {
           ~~~~~~~~~~~~~~~

src/slashes/uptime.ts:7:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'seconds' must be of type 'any', but here has type 'number'.

7     var seconds = Math.floor(seconds % 60);
          ~~~~~~~

  src/slashes/uptime.ts:3:26
    3 function secondsToString(seconds) {
                               ~~~~~~~
    'seconds' was also declared here.

src/slashes/uptime.ts:15:9 - error TS2322: Type 'string' is not assignable to type 'number'.

15         hours = "0" + hours;
           ~~~~~

src/slashes/uptime.ts:18:9 - error TS2322: Type 'string' is not assignable to type 'number'.

18         minutes = "0" + minutes;
           ~~~~~~~

src/slashhandler.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'configs'.

1 const configs = require('./configs.json')
        ~~~~~~~

  src/bot.ts:3:7
    3 const configs = require('./configs.json')
            ~~~~~~~
    'configs' was also declared here.

src/slashhandler.ts:2:7 - error TS2451: Cannot redeclare block-scoped variable 'fs'.

2 const fs = require('fs');
        ~~

  src/bot.ts:4:7
    4 const fs = require("fs")
            ~~
    'fs' was also declared here.

src/slashhandler.ts:4:5 - error TS2451: Cannot redeclare block-scoped variable 'cache'.

4 let cache = []
      ~~~~~

  src/command.ts:2:5
    2 let cache = []
          ~~~~~
    'cache' was also declared here.

src/slashhandler.ts:5:5 - error TS2451: Cannot redeclare block-scoped variable 'prefix'.

5 let prefix = configs.prefix
      ~~~~~~

  src/command.ts:3:5
    3 let prefix = "blub"
          ~~~~~~
    'prefix' was also declared here.

src/Utilities.ts:6:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'seconds' must be of type 'any', but here has type 'number'.

6         var seconds = Math.floor(seconds % 60);
              ~~~~~~~

  src/Utilities.ts:2:21
    2     secondsToString(seconds) {
                          ~~~~~~~
    'seconds' was also declared here.

src/Utilities.ts:14:13 - error TS2322: Type 'string' is not assignable to type 'number'.

14             hours = "0" + hours;
               ~~~~~

src/Utilities.ts:17:13 - error TS2322: Type 'string' is not assignable to type 'number'.

17             minutes = "0" + minutes;
               ~~~~~~~


Found 96 errors.

**Comment by SkyBlockDev** [comment]
yeah ts finds all your mistakes and now you have to fix em this is normal

**Comment by SirObby** [comment]
this dosent happen when I run it through Njs though

**Comment by SirObby** [comment]
And im just confused ngl

**Comment by SkyBlockDev** [comment]
> this dosent happen when I run it through Njs though

you need to add types and stuff it will be worth it

**Comment by SirObby** [comment]
Cant you do it?

**Comment by SirObby** [comment]
I'm closing this cause I've made fixes on my PC

**Pull request merged**
